import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { FirebaseAppProvider } from "reactfire";

import firebaseApp from "~/lib/firebase";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <FirebaseAppProvider firebaseApp={firebaseApp}>
          {children}
        </FirebaseAppProvider>
      </body>
    </html>
  );
}
