import "~/styles/globals.css";

import { type ReactElement } from "react";
import { Inter } from "next/font/google";

import { ReactFireProvider } from "~/app/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Enimo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: ReactElement }) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <ReactFireProvider>{children}</ReactFireProvider>
      </body>
    </html>
  );
}
